# Generated by Django 3.2.8 on 2021-10-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211023_1231'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidcustomer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceprice'),
        ),
    ]
