# Generated by Django 3.2.8 on 2021-10-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211023_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprice',
            name='description',
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='service_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
